# Generated by Django 2.2.5 on 2020-01-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_title', models.CharField(max_length=200)),
                ('recipe_content', models.TextField()),
                ('recipe_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
